<Project>
  <Import Project="..\..\Directory.Build.props" />
  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <EnableTrimAnalyzer>false</EnableTrimAnalyzer>
    <EnableSingleFileAnalyzer>false</EnableSingleFileAnalyzer>
    <IsPackable>false</IsPackable>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
</Project>
